name: "Setup repo and run CI"
description: "Prepare repository and all dependencies"

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2.4.0

    - name: Setup bun
      uses: oven-sh/setup-bun@v1
      with:
          bun-version: latest

    - name: Install packages
      run: bun install --frozen-lockfile

    - name: Build code
      run: bun run build

    - name: CI
      shell: bash
      run: bun run ci && bun run typecheck
