import fs from "node:fs";

const localBaseUrl = "http://localhost:8080";
const remoteBaseUrl = "https://api.witness.co";
const res = await fetch(`${remoteBaseUrl}/swagger/json`);
const spec = await res.json();

// Write the spec to spec.ts with the following contents:
// export default <spec> as const;
fs.writeFileSync(
	"src/openapi.ts",
	`// GENERATED BY pnpm run generate:openapi\nexport default ${JSON.stringify(
		spec,
	)} as const;`,
);
